### PR TITLE
Fixed Problem 1 example for 1-based indexing

### PR DESCRIPTION
**Pull request by svilupp**
Fixing the provided example for Julia's 1-based indexing

### CODE REVIEW

**Comment by RexWzh** [comment]
Thanks, @svilupp, for your contribution.
The problem text aligns with the one on leetcode.com; specifically, for this instance, [Two Sum Problem Description](https://leetcode.com/problems/two-sum/description/).

Moreover, I believe that managing indices is more a concern of algorithm design and should not be a fixed requirement within the problem statement.

**Comment by svilupp** [comment]
I'm not sure I follow your explanation.

Are you saying that it's okay that the examples provided do not execute correctly? 
Eg, `Because nums[0] + nums[1] == 9, we return [0, 1]` will throw an out of bounds error.

Or maybe you're saying that it should be exactly the same as Python (0-based indexing), in which case the solution is wrong because it's using 1-based `enumerate` for indexing: `for (i, n) in enumerate(nums)`.

Or maybe you meant something else? I merely pointing out that the solution doesn't align with the examples.

**Comment by RexWzh** [comment]
I mean, you can treat it more like pseudocode rather than real code.
For instance, the syntax `nums = [3,2,4]` is not valid in C, but it is acceptable for illustrating examples.

image

**Comment by RexWzh** [comment]
Contributions are warmly welcomed, and here's how to get started:

1. First, create a new file for an unsolved problem:
```bash
cd LeetCode.jl
# Generate a new solution file for unsolved problem 38
julia scripts/newsolution.jl 38
```

2. Next, write the solution and tests in `scripts/presolution/38.xxx.jl`.

3. Then, convert the draft solution and tests into their final form using the following command:
```bash
julia scripts/submit.jl 38
```

After thoroughly testing the solution, commit the changes and push them to the repository using `git`.

---

Other types of contributions are also appreciated. For instance, one can add more problem templates from leetcode.com (most of them are generated through scraping) or improve the existing scripts in the `scripts` directory.

Thank you for the support and collaboration!

**Comment by svilupp** [comment]
Thank you for the explanation! I misunderstood the purpose / conditions — I assumed it’s meant to be valid Julia code for newcomers, but I understand now that you prioritize the consistency with LC descriptions.

I noticed it because I was building a synthetic data set of code optimization feedback (for finetuning an LLM) and I had to add a 3-round self-reflection to fix a lot of these examples to be runnable. Good to know for the future!

**Comment by RexWzh** [comment]
Oh, I see. You're building a synthetic dataset of code for fine-tuning an LLM.

The texts in `src/problems` are simply duplicates from leetcode.com without any adaptation to Julia. It requires the same effort to convert the text from leetcode.com to Julia style. However, the codes and tests in this repository could still be quite helpful.

**Pull request closed without merging**
