### PR TITLE
add solutions and edit solution 3

### PR DESCRIPTION
**Pull request by RexWzh**
Abstract:
   - add solutions to 26 questions: 19, 21, 36, 53, 55, 63, 64, 70, 113, 118, 121, 167, 198, 213, 219, 283, 344, 350, 387, 746, 876, 977, 1220, 1332, 1345,1567
   - edit original solution of question 3

---

The original solution to [question 3](https://leetcode-cn.com/problems/longest-substring-without-repeating-characters/) failed for some cases:
```julia
@test length_of_longest_substring("abac") == 3
```

---

The following Solutions are first implemented in Python, tested by LeetCode, and then implemented in Julia. The last columns are brief discussions written by me, with reference to Python and Julia code.

question | filename | function | link to leetcode discussion
:-: | :-: | :-: | :-:
19 | remove-nth-node-from-end-of-list | remove_nth_from_end | [solution to 19](https://leetcode-cn.com/problems/remove-nth-node-from-end-of-list/solution/19-shan-chu-lian-biao-de-dao-shu-di-n-ge-jkcr/)
19 | remove-nth-node-from-end-of-list | remove_nth_from_end_by_double_pointers | [solution to 19](https://leetcode-cn.com/problems/remove-nth-node-from-end-of-list/solution/19-shan-chu-lian-biao-de-dao-shu-di-n-ge-jkcr/)
21 | merge-two-sorted-lists | merge_two_lists | [solution to 21](https://leetcode-cn.com/problems/merge-two-sorted-lists/solution/21-he-bing-liang-ge-you-xu-lian-biao-by-8uayp/)
36 | valid-sudoku | is_valid_sudoku | [solution to 36](https://leetcode-cn.com/problems/valid-sudoku/solution/36-you-xiao-de-shu-du-by-rex-rs-40ht/)
53 | maximum-subarray | maximum_subarray | [solution to 53](https://leetcode-cn.com/problems/maximum-subarray/solution/53-zui-da-zi-shu-zu-he-by-rex-rs-9gu6/)
55 | jump-game | can_jump | [solution to 55](https://leetcode-cn.com/problems/jump-game/solution/55-tiao-yue-you-xi-by-rex-rs-w50c/)
63 | unique-paths-ii | unique_path_with_obstacles_63 | [solution to 63](https://leetcode-cn.com/problems/unique-paths-ii/solution/63-bu-tong-lu-jing-ii-by-rex-rs-60to/)
64 | minimum-path-sum | min_path_sum | [solution to 64](https://leetcode-cn.com/problems/minimum-path-sum/solution/64-zui-xiao-lu-jing-he-by-rex-rs-s1vt/)
70 | climbing-stairs | climbing_stairs | [solution to 70](https://leetcode-cn.com/problems/climbing-stairs/solution/70-pa-lou-ti-by-rex-rs-0rj2/) |
113 | path-sum-ii | path_sum_113 | [solution to 113](https://leetcode-cn.com/problems/path-sum-ii/solution/113-lu-jing-zong-he-ii-by-rex-rs-p52p/)
118 | pascals-triangle | pascals_triangle | [solution to 118](https://leetcode-cn.com/problems/pascals-triangle/solution/118-yang-hui-san-jiao-by-rex-rs-txbd/)
121 | best-time-to-buy-and-sell-stock | max_profit_121 | [solution to 121](https://leetcode-cn.com/problems/best-time-to-buy-and-sell-stock/solution/121-mai-mai-gu-piao-de-zui-jia-shi-ji-by-bdfl/)
167 | two-sum-ii-input-array-is-sorted | two_sum_167 | [solution to 167](https://leetcode-cn.com/problems/two-sum-ii-input-array-is-sorted/solution/167-liang-shu-zhi-he-ii-shu-ru-you-xu-sh-mh6l/)
198 | house-robber | rob_198 | [solution to 198](https://leetcode-cn.com/problems/house-robber/solution/198-da-jia-jie-she-by-rex-rs-xy8m/)
213 | house-robber-ii | rob_213 | [solution to 213](https://leetcode-cn.com/problems/house-robber-ii/solution/213-da-jia-jie-she-ii-by-rex-rs-4gnd/)
219 | contains-duplicate-ii | contains_nearby_duplicate | [solution to 219](https://leetcode-cn.com/problems/contains-duplicate-ii/solution/219-cun-zai-zhong-fu-yuan-su-ii-by-rex-r-enyx/)
283 | move-zeroes | move_zeros! | [solution to 283](https://leetcode-cn.com/problems/move-zeroes/solution/283-yi-dong-ling-by-rex-rs-8kc3/)
344 | reverse-string | reverse_string! | [solution to 344](https://leetcode-cn.com/problems/reverse-string/solution/344-fan-zhuan-zi-fu-chuan-by-rex-rs-f0a0/)
350 | intersection-of-two-arrays-ii | intersection_of_arrays | [solution to 350](https://leetcode-cn.com/problems/intersection-of-two-arrays-ii/solution/350-liang-ge-shu-zu-de-jiao-ji-ii-by-rex-5e67/)
387 | first-unique-character-in-a-string | first_unique_char | [solution to 387](https://leetcode-cn.com/problems/first-unique-character-in-a-string/solution/387-zi-fu-chuan-zhong-de-di-yi-ge-wei-yi-6s01/)
746 | min-cost-climbing-stairs | min_cost_climbing_stairs | [solution to 746](https://leetcode-cn.com/problems/min-cost-climbing-stairs/solution/746-shi-yong-zui-xiao-hua-fei-pa-lou-ti-d2vq5/)
876 | middle-of-the-linked-list | middle_node | [solution to 876](https://leetcode-cn.com/problems/middle-of-the-linked-list/solution/876-lian-biao-de-zhong-jian-jie-dian-by-419j4/)
876 | middle-of-the-linked-list | middle_node_by_double_pointers | [solution to 876](https://leetcode-cn.com/problems/middle-of-the-linked-list/solution/876-lian-biao-de-zhong-jian-jie-dian-by-419j4/)
977 | squares-of-a-sorted-array | squares_of_a_sorted_array | [solution to 977](https://leetcode-cn.com/problems/squares-of-a-sorted-array/solution/977-you-xu-shu-zu-de-ping-fang-by-rex-rs-u2l0/)
1220 | count-vowels-permutation | count_vowel_permutation| [solution to 1220](https://leetcode-cn.com/problems/count-vowels-permutation/solution/1220-tong-ji-yuan-yin-zi-mu-xu-lie-de-sh-wxxp/)
1332 | remove-palindromic-subsequences | remove_palindromic_subsequences | [solution to 1332](https://leetcode-cn.com/problems/remove-palindromic-subsequences/solution/1332-shan-chu-hui-wen-zi-xu-lie-by-rex-r-f0r0/)
1345 | jump-game-iv | min_jumps_1345 | [solution to 1345](https://leetcode-cn.com/problems/jump-game-iv/solution/1345-tiao-yue-you-xi-iv-by-rex-rs-2fmd/)
1567 | maximum-length-of-subarray-with-positive-product | get_max_len | [solution to 1567](https://leetcode-cn.com/problems/maximum-length-of-subarray-with-positive-product/solution/1567-cheng-ji-wei-zheng-shu-de-zui-chang-lje0/)

### CODE REVIEW

**Comment by findmyway** [comment]
Amazing work!

Ping me when you think it's ready to merge.

**Comment by johnnychen94** [comment]
I notice that this PR has the potential to grow infinitely. By all means this is great. I just want to point out that it's probably a good idea to merge this PR eagerly to avoid potential conflicts.

**Comment by Moelf** [comment]
it's already going infinite...

**Comment by RexWzh** [comment]
> I notice that this PR has the potential to grow infinitely. By all means this is great. I just want to point out that it's probably a good idea to merge this PR eagerly to avoid potential conflicts.

Ok, after scripting checks and a little manual checking, it feels ready to commit.

---

These are the problems I have solved recently. For the convenience of coding, I write them in my [repository](https://github.com/RexWzh/leetcode_note.jl) first. And today, I write some scripts to standardize the formats, so they look much in a sudden.

**Comment by johnnychen94** [comment]
53 commits is a huge PR!

**Pull request merged**
